# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
  config.vm.box = "ubuntu/bionic64"
  #config.vm.network "private_network", ip: "192.168.100.55"

   config.vm.provider "virtualbox" do |vb|
     vb.memory = "8192"
     vb.cpus = 4
   end
   config.vm.provision "shell", inline: <<-SHELL
     curl -LO https://storage.googleapis.com/kubernetes-release/release/v1.19.0/bin/linux/amd64/kubectl
     chmod +x ./kubectl
     sudo mv ./kubectl /usr/bin/kubectl
     wget https://github.com/derailed/k9s/releases/download/v0.22.1/k9s_Linux_x86_64.tar.gz
     tar xf k9s_Linux_x86_64.tar.gz
     chmod +x k9s
     sudo mv  k9s /usr/local/bin/
     echo "export KUBECONFIG=/etc/rancher/k3s/k3s.yaml" >> /home/vagrant/.bashrc
     curl -sfL https://raw.githubusercontent.com/Gsantomaggio/k8s/wip/k3s-rmq/install |  bash -
   SHELL
end
