apiVersion: skaffold/v2alpha3
kind: Config
metadata:
  name: code
build:
  artifacts:
  - image: books
    context: ../ms_books
deploy:
  kubectl:
    manifests:
    - deploy/book.yaml
    - deploy/gateway.yaml
    - deploy/route.yaml
