kind: Service
apiVersion: v1
metadata:
  name: rabbitmq-app
spec:
  type: NodePort
  ports:
   - name: http
     protocol: TCP
     port: 15672
   - name: amqp
     protocol: TCP
     port: 5672
   - name: epmd
     protocol: TCP
     port: 4369
  selector:
    app: rabbitmq-app
