stages:
- name: Create Docker Image
  steps:
  - publishImageConfig:
      dockerfilePath: ml/kubeflow/Dockerfile
      buildContext: ml/kubeflow/
      tag: gsantomaggio/sklearn
      pushRemote: true
      registry: index.docker.io
  - runScriptConfig:
      image: python:latest
      shellScript: |-
        gitjson='{"name":"iris","description":"iris","backendtype":"kubeflow" }'
        curl  -i -X POST -H "Content-Type: multipart/form-data" -F "template=@$file/ml/kubeflow/classification_v1.py" \
                 -F data="$gitjson" \
                 -X POST http://ai-orchestrator.ai-orchestrator/api/template
timeout: 60
notification: {}
