apiVersion: v1
kind: Service
metadata:
  name: books-service
  labels:
    app: books-app
spec:
  clusterIP: None
  ports:
    - port: 2200
      name: books-app
  selector:
    app: books-app
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: books
  labels:
    app: books-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: books-app
  template:
    metadata:
      labels:
        app: books-app
    spec:
      containers:
        - name: webbooks
          image: books
          ports:
            - containerPort: 2200
