apiVersion: v1
kind: Service
metadata:
  name: books-service
  labels:
    app: books-app
spec:
  clusterIP: None
  ports:
    - port: 2200
      name: books-app
    - port: 2100
      name: food-app
    - port: 2000
      name: static-app
  selector:
    app: store
