apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: rabbitmq-app-gateway
spec:
  maxReplicas: 5
  minReplicas: 1
  scaleTargetRef:
    apiVersion: apps/v1beta1
    kind: Deployment
    name: rabbitmq-app-gateway
  targetCPUUtilizationPercentage: 80
status:
  currentCPUUtilizationPercentage: 0
  currentReplicas: 1
  desiredReplicas: 1
---
apiVersion: v1
kind: Service
metadata:
  name: rabbitmq-app-gateway
  labels:
    istio: rabbitmq-app-gateway
    app: rabbitmq-app-gateway
spec:
  type: LoadBalancer
  ports:
  - port: 80
    name: http
  - port: 443
    name: https
  selector:
    app: rabbitmq-app-gateway
    istio: rabbitmq-app-gateway