apiVersion: v1
kind: Service
metadata:
  name: food-service
  labels:
    app: food-app
spec:
  clusterIP: None
  ports:
    - port: 2100
      name: food-app
  selector:
    app: food-app
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: food
  labels:
    app: food-app

spec:
  replicas: 1
  selector:
    matchLabels:
      app: food-app
  template:
    metadata:
      labels:
        app: food-app
    spec:
      containers:
        - name: webfood
          image: food
          ports:
            - containerPort: 2100
