apiVersion: v1
kind: Service
metadata:
  name: prometheus-service
  annotations:
      prometheus.io/scrape: 'true'
      prometheus.io/port:   '9090'

spec:
  selector: 
    app: prometheus-server
  clusterIP: None
  ports:
    - port: 9090
      name: prometheus-app